### ISSUE TITLE
main_a2c.py doesn't run because of missing gym_pomdps module

### ISSUE THREAD

**Issue by amitfishy** [abaisero/asym-rlpo#1]
Hello, thanks for providing code for the paper. I'm able to install all the requirements, but I still get an error while trying to run `main_a2c.py`

```
python main_a2c.py

Traceback (most recent call last):
  File "/home/fishy/python_ws/aais-baisero/code/asym-rlpo/main_a2c.py", line 16, in <module>
    from asym_rlpo.algorithms import A2C_ABC, make_a2c_algorithm
  File "/home/fishy/python_ws/aais-baisero/code/asym-rlpo/asym_rlpo/algorithms/__init__.py", line 3, in <module>
    from asym_rlpo.envs import Environment
  File "/home/fishy/python_ws/aais-baisero/code/asym-rlpo/asym_rlpo/envs/__init__.py", line 12, in <module>
    from .env_gym import make_gym_env
  File "/home/fishy/python_ws/aais-baisero/code/asym-rlpo/asym_rlpo/envs/env_gym.py", line 8, in <module>
    import gym_pomdps
ModuleNotFoundError: No module named 'gym_pomdps'

```

Not sure where to get this module exactly! I'm just trying to reproduce some experiments from your paper: 
https://arxiv.org/abs/2105.11674

Thanks!

**Comment by abaisero** [comment]
Hi, thanks for raising this issue to my attention;  this code relies on some of my other repositories, but I just noticed that this is not documented anywhere;  shortly, I'll update the readme to include this information.

**Comment by amitfishy** [comment]
Thank you, this helps. Could you also please tell me how I could use the environments in ;
https://github.com/abaisero/gym-pomdps/tree/master/gym_pomdps/pomdps

I've tried giving the filename as follows:
`python main_a2c.py heavenhell_3 a2c`

But it does not pick up the environment name. Might be nice to have this in the readme too ;)

**Comment by abaisero** [comment]
Hello Amit,

I'm assuming you found the solution to this, since I could not see a github
issue on this topic;  if you still need help on this, please open a github
issue, it makes it a lot easier to track questions, both for me and for
future users.

Thanks!
Andrea

**Comment by amitfishy** [comment]
Yes I did! I didn't raise another issue because your corrections were sufficient to get things to work.

Thanks!
Amit
