### ISSUE TITLE
Memory related issues in Shopping envs

### ISSUE THREAD

**Issue by amitfishy** [abaisero/asym-rlpo#3]
Hello again!

I've been trying to run experiments on the following shopping environments:
```
Shopping 5    - POMDP-shopping_5-episodic-v1
Shopping 6    - POMDP-shopping_6-episodic-v1
```
But I keep having some strange issues related to memory. Not sure why, but even if I just simply load the env with a `gym.make` call it causes the system to hang (sometimes). Did you face similar issues while running experiments on these environments?

Thanks!
Amit

**Comment by abaisero** [comment]
Do you just mean that it takes a bit to load, or that it crashes while loading?  I don't recall the specifics of those two domains, but here is a generic explanation about how the POMDP-XXX domains are implemented and loaded:

The POMDP-XXX domains come from the [gym-pomdps](https://github.com/abaisero/gym-pomdps) repository, and are implemented in a way that is particularly memory-inefficient;  basically that repository creates a gym interface for environments defined in the classic [POMDP file format](http://pomdp.org/code/pomdp-file-spec.html).  This means that loading the environment requires loading full tables of probabilities and values, some of which contain as many as |S|^2 |A| |O| values, which can be pretty big.  For this reason, some of these domains might take some time to load, I don't pay much attention to that, but I think it might take up to a few minutes, maybe? others might just require more memory that your machine actually has, which leads to a crash;  sadly that's just inevitable given the way that these environments are specified.

That's probably what is happening.  As long as it just hangs for a little bit, then I think that's just to be expected.  Let me know if this answers your question or not.

**Comment by amitfishy** [comment]
Thanks for the response.

I was trying a machine with 4G and that must have been too small. I will try something larger and get back to you!

**Comment by amitfishy** [comment]
A machine with 32G was enough for both those environments. Thanks for pointing out the issue.
