### ISSUE TITLE
Making the baseline data plotted in the graphs available in this repo

### ISSUE THREAD

**Issue by amitfishy** [abaisero/asym-rlpo#6]
Hello!

We have a paper we're working on where we would like to make comparisons from the baselines in your paper. Particularly the `A2C-asym-hs` and the `A2C` baselines for the following envs:
```
Heaven-Hell-3
Heaven-Hell-4
Shopping-5
Shopping-6
Car-Flag
Cleaner
```
I would really appreciate it if you could make the numerical data that is plotted available in any format in this repo (or just share it with me if you don't want to make it public). I just need it to compare plots!

Thank you
Amit

**Comment by abaisero** [comment]
Hello Amit,

I can work in the next days to collect that data and send it over;  I do warn you though, that a more fair comparison would be if you would implement the method yourself, to have all non-relevant aspects of the training (models, training schedules, rates, hacks, etc) be the same between different methods.

Do you have a timeline by which you need this data?

**Comment by amitfishy** [comment]
I do agree with you about that, we're trying to really just show that performance is comparable rather than emphasize that small incremental improvements are truly indicative of a "better" algorithm.

Feel free to share it after the holidays, and happy holidays :)

**Comment by amitfishy** [comment]
Hi @abaisero , just a reminder regarding this!

**Comment by abaisero** [comment]
Hello Amit;  my apologies for delaying this.  I'm going to do this next, hopefully it shouldn't be too hard.

**Comment by abaisero** [comment]
Hello Amit;  find the requested data in the following link:  https://www.dropbox.com/scl/fo/z0rnc0z1amd8buaa5sofy/h?dl=0&rlkey=p01ii4deijnerztcrl73g42i1

The format should be pretty straightforward upon inspection, but do let me know if you need any help interpreting it.  Each `.pk` file contains the results of 20 independent runs, which need to be aggregated separately.

Feel free to re-open this issue with any clarifying questions or additional requests.
